DROP TABLE IF EXISTS story_blocks CASCADE;
CREATE TABLE story_blocks (
  id SERIAL PRIMARY KEY NOT NULL,
  story_id INTEGER REFERENCES stories(id) ON DELETE CASCADE,
  completed BOOLEAN NOT NULL DEFAULT FALSE
);
